# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"\"\n\x0bTestRequest\x12\x13\n\x0btest_before\x18\x01 \x01(\t\"\"\n\x0cTestResponse\x12\x12\n\ntest_after\x18\x01 \x01(\t\"X\n\x06Metric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x10\n\x08\x61gent_id\x18\x04 \x01(\t\x12\x0c\n\x04unit\x18\x05 \x01(\t\"5\n\x14SubmitMetricsRequest\x12\x1d\n\x07metrics\x18\x01 \x03(\x0b\x32\x0c.test.Metric\"9\n\x15SubmitMetricsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"`\n\x11GetMetricsRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x13\n\x0bmetric_name\x18\x02 \x01(\t\x12\x12\n\nstart_time\x18\x03 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\x03\"3\n\x12GetMetricsResponse\x12\x1d\n\x07metrics\x18\x01 \x03(\x0b\x32\x0c.test.Metric2;\n\x04Test\x12\x33\n\nTestMethod\x12\x11.test.TestRequest\x1a\x12.test.TestResponse2\x9b\x01\n\x0eMetricsService\x12H\n\rSubmitMetrics\x12\x1a.test.SubmitMetricsRequest\x1a\x1b.test.SubmitMetricsResponse\x12?\n\nGetMetrics\x12\x17.test.GetMetricsRequest\x1a\x18.test.GetMetricsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTREQUEST']._serialized_start=20
  _globals['_TESTREQUEST']._serialized_end=54
  _globals['_TESTRESPONSE']._serialized_start=56
  _globals['_TESTRESPONSE']._serialized_end=90
  _globals['_METRIC']._serialized_start=92
  _globals['_METRIC']._serialized_end=180
  _globals['_SUBMITMETRICSREQUEST']._serialized_start=182
  _globals['_SUBMITMETRICSREQUEST']._serialized_end=235
  _globals['_SUBMITMETRICSRESPONSE']._serialized_start=237
  _globals['_SUBMITMETRICSRESPONSE']._serialized_end=294
  _globals['_GETMETRICSREQUEST']._serialized_start=296
  _globals['_GETMETRICSREQUEST']._serialized_end=392
  _globals['_GETMETRICSRESPONSE']._serialized_start=394
  _globals['_GETMETRICSRESPONSE']._serialized_end=445
  _globals['_TEST']._serialized_start=447
  _globals['_TEST']._serialized_end=506
  _globals['_METRICSSERVICE']._serialized_start=509
  _globals['_METRICSSERVICE']._serialized_end=664
# @@protoc_insertion_point(module_scope)
